language : "cpp"
generator_path : "/home/workspace/yarpgen-pro/build/yarpgen"
testing_path : "/home/workspace/Testing/"
timeout : 30
run_count : 100

compiler :
  - "g++"
  - "clang++"

optimization :
  - "-O0"
  - "-O1"
  - "-Os"
  - "-O2"
  - "-O3"
  - "-Ofast"

extra_option :
  - "-std=c++14"

march:
  - "-march=alderlake"
  - "-march=amdfam10"
  - "-march=arrowlake"
  - "-march=arrowlake-s"
  - "-march=athlon-fx"
  - "-march=athlon64"
  - "-march=athlon64-sse3"
  - "-march=atom"
  - "-march=barcelona"
  - "-march=bdver1"
  - "-march=bdver2"
  - "-march=bdver3"
  - "-march=bdver4"
  - "-march=bonnell"
  - "-march=broadwell"
  - "-march=btver1"
  - "-march=btver2"
  - "-march=cannonlake"
  - "-march=cascadelake"
  - "-march=clearwaterforest"
  - "-march=cooperlake"
  - "-march=core-avx-i"
  - "-march=core-avx2"
  - "-march=core2"
  - "-march=corei7"
  - "-march=corei7-avx"
  - "-march=emeraldrapids"
  - "-march=goldmont"
  - "-march=goldmont-plus"
  - "-march=gracemont"
  - "-march=grandridge"
  - "-march=graniterapids"
  - "-march=graniterapids-d"
  - "-march=haswell"
  - "-march=icelake-client"
  - "-march=icelake-server"
  - "-march=ivybridge"
  - "-march=k8"
  - "-march=k8-sse3"
  - "-march=knl"
  - "-march=knm"
  - "-march=lunarlake"
  - "-march=meteorlake"
  - "-march=nehalem"
  - "-march=nocona"
  - "-march=opteron"
  - "-march=opteron-sse3"
  - "-march=pantherlake"
  - "-march=raptorlake"
  - "-march=rocketlake"
  - "-march=sandybridge"
  - "-march=sapphirerapids"
  - "-march=sierraforest"
  - "-march=silvermont"
  - "-march=skylake"
  - "-march=skylake-avx512"
  - "-march=slm"
  - "-march=tigerlake"
  - "-march=tremont"
  - "-march=westmere"
  - "-march=x86-64"
  - "-march=x86-64-v2"
  - "-march=x86-64-v3"
  - "-march=x86-64-v4"
  - "-march=znver1"
  - "-march=znver2"
  - "-march=znver3"
  - "-march=znver4"
  - "-march=znver5"